from tkinter import *
root = Tk()
root.title("Hi,Good Morning")
def submit():
    print("Welcome ",e.get())
def New():
    print("Your Experience",v.get())
def Main():
    print("Our teaching faculty",v1.get())
def mm():
    print("Enivorment",v2.get())
def my():
    print("How rate our aptron",v3.get())
def quit():
    print("Thanks for your feedback")
    root.destroy()
e = Entry(root)
e.grid(row = 1,column = 2,sticky = W)
a = Entry(root)
b = Entry(root)
c = Entry(root)
d = Entry(root)
f = Entry(root)
v = IntVar()
v1 = IntVar()
v2 = IntVar()
v3 = IntVar()
v.set(1)
v1.set(1)
v2.set(1)
v3.set(1)
Label(root,text = "Enter your Name",width = 15).grid(row = 1,column = 0)
Button(root,text = "Enter",command = submit,justify = "left",activebackground = "grey",width = 6,bd = 1,font = "monochrome",relief = SUNKEN).grid(row = 2,column = 0)
Label(root,text = "Your Experience",width = 15).grid(row = 3,column = 0)
Radiobutton(root,text = "*",variable = v, value = 1,command = New).grid(row = 4,column = 2)
Radiobutton(root,text = "**",variable = v, value = 2,command = New).grid(row = 5,column = 2)
Radiobutton(root,text = "***",variable = v, value = 3,command = New).grid(row = 6,column = 2)
Radiobutton(root,text = "****",variable = v, value = 4,command = New).grid(row = 7,column = 2)
Radiobutton(root,text = "*****",variable = v, value = 5,command = New).grid(row = 8,column = 2)
Label(root,text = "Our teaching faculty",width = 15).grid(row = 9,column = 0)
Radiobutton(root,text = "*",variable = v1, value = 1,command = Main).grid(row = 10,column = 2)
Radiobutton(root,text = "**",variable = v1, value = 2,command = Main).grid(row = 11,column = 2)
Radiobutton(root,text = "***",variable = v1, value = 3,command = Main).grid(row = 12,column = 2)
Radiobutton(root,text = "****",variable = v1, value = 4,command = Main).grid(row = 13,column = 2)
Radiobutton(root,text = "*****",variable = v1, value = 5,command = Main).grid(row = 14,column = 2)
Label(root,text = "Enivorment",width = 15).grid(row = 15,column = 0)
Radiobutton(root,text = "*",variable = v2, value = 1,command = mm).grid(row = 16,column = 2)
Radiobutton(root,text = "**",variable = v2, value = 2,command = mm).grid(row = 17,column = 2)
Radiobutton(root,text = "***",variable = v2, value = 3,command = mm).grid(row = 18,column = 2)
Radiobutton(root,text = "****",variable = v2, value = 4,command = mm).grid(row = 19,column = 2)
Radiobutton(root,text = "*****",variable = v2, value = 5,command = mm).grid(row = 20,column = 2)
Label(root,text = "How rate our aptron",width = 15).grid(row = 21,column = 0)
Radiobutton(root,text = "*",variable = v3 , value = 1,command = my).grid(row = 22,column = 2)
Radiobutton(root,text = "**",variable = v3 , value = 2,command = my).grid(row = 23,column = 2)
Radiobutton(root,text = "***",variable = v3 , value = 3,command = my).grid(row = 24,column = 2)
Radiobutton(root,text = "****",variable = v3 , value = 4,command = my).grid(row = 25,column = 2)
Radiobutton(root,text = "*****",variable = v3 , value = 5,command = my).grid(row = 26,column = 2)
Button(root,text = "Submit",command = quit,justify = "left",activebackground = "blue",activeforeground = "pink",width = 6,bd = 1,font = "monochrome",relief = SUNKEN).grid(row = 28,column = 4)
root.mainloop()
